sudo: false
language: python
python:
  - 2.7
install:
  - python bootstrap.py
  - bin/buildout -N -q
script:
- bin/test
- bin/i18ndude find-untranslated src/i18ndude/tests
after_failure:
  - bin/buildout annotate
